dataset_name: MNIST

labeled_num: 100
learning_rate: 3.e-4
batch_size: 100

architecture:
  layers_num: 3
  input_dim: 784
  latent_dim: 10
  # latent_dim: 2
  hidden_dim: 1024

loss_weights:
  distance: 0.
  supervised: 10.
  cw: 5.

init_radius: 10
rng_seed: 20
